---
- hosts: kube-masters
  remote_user: kspx
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
  - vars.yml
  roles:
  - ztest1
  - commons/base
  - nodejs
  #- haproxy
 # - apache2
 # - php7.2
  #- keepalived
  # - docker
  # - kubernetes/master
            
